name: feedback_app
description: Flutter feedback application for mobile using firebase as Backend.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2

  #state_management
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1


  #firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1

  #local storage
  shared_preferences: ^2.2.1

  #dependency injection
  get_it: ^7.6.4

  #navigation
  go_router: ^10.1.2

  # for unique id
  uuid: 3.0.6

  # date conversion
  intl: ^0.18.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: 2.4.1
  flutter_launcher_icons: ^0.13.1
  test:
  fake_cloud_firestore: ^2.4.1+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"




flutter:

  uses-material-design: true

  assets:
     - assets/icons/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
